// src/components/product_data.jsx

const product_data = {
    boltSeals: [
      {
        id: 1,
        product_name: "Bolt Seal 1",
        description: "High-security bolt seal...",
        price: 100,
        currency: "GHC",
        thumb: require('../Media/PsSQ.jpg'),
      },
      {
        id: 1,
        product_name: "Bolt Seal 2",
        description: "High-security bolt seal...",
        price: 100,
        currency: "GHC",
        thumb: require('../Media/TRYB2.png'),
      },
      {
        id: 1,
        product_name: "Bolt Seal 3",
        description: "High-security bolt seal...",
        price: 100,
        currency: "GHC",
        thumb: require('../Media/TRYB.png'),
      },
      {
        id: 1,
        product_name: "Bolt Seal 4",
        description: "High-security bolt seal...",
        price: 100,
        currency: "GHC",
        thumb: require('../Media/p7.jpg'),
      },
      {
        id: 1,
        product_name: "Bolt Seal 1",
        description: "High-security bolt seal...",
        price: 100,
        currency: "GHC",
        thumb: require('../Media/PsSQ.jpg'),
      },
      {
        id: 1,
        product_name: "Bolt Seal 2",
        description: "High-security bolt seal...",
        price: 100,
        currency: "GHC",
        thumb: require('../Media/TRYB2.png'),
      },
      {
        id: 1,
        product_name: "Bolt Seal 3",
        description: "High-security bolt seal...",
        price: 100,
        currency: "GHC",
        thumb: require('../Media/TRYB.png'),
      },
      {
        id: 1,
        product_name: "Bolt Seal 4",
        description: "High-security bolt seal...",
        price: 100,
        currency: "GHC",
        thumb: require('../Media/p7.jpg'),
      },
      
      // More bolt seals...
    ],
    cableSeals: [
      {
        id: 2,
        product_name: "Cable Seal 1",
        description: "Durable cable seal...",
        price: 80,
        currency: "GHC",
        thumb: require('../Media/p2.jpg'),
      },
      {
        id: 2,
        product_name: "Cable Seal 1",
        description: "Durable cable seal...",
        price: 80,
        currency: "GHC",
        thumb: require('../Media/p2.jpg'),
      },
      {
        id: 2,
        product_name: "Cable Seal 1",
        description: "Durable cable seal...",
        price: 80,
        currency: "GHC",
        thumb: require('../Media/p2.jpg'),
      },
      {
        id: 2,
        product_name: "Cable Seal 1",
        description: "Durable cable seal...",
        price: 80,
        currency: "GHC",
        thumb: require('../Media/p2.jpg'),
      },
      {
        id: 2,
        product_name: "Cable Seal 1",
        description: "Durable cable seal...",
        price: 80,
        currency: "GHC",
        thumb: require('../Media/p2.jpg'),
      },
      {
        id: 2,
        product_name: "Cable Seal 1",
        description: "Durable cable seal...",
        price: 80,
        currency: "GHC",
        thumb: require('../Media/p2.jpg'),
      },
      {
        id: 2,
        product_name: "Cable Seal 1",
        description: "Durable cable seal...",
        price: 80,
        currency: "GHC",
        thumb: require('../Media/p2.jpg'),
      },
      {
        id: 2,
        product_name: "Cable Seal 1",
        description: "Durable cable seal...",
        price: 80,
        currency: "GHC",
        thumb: require('../Media/p2.jpg'),
      },
      // More cable seals...
    ],
    plasticSeals: [
      {
        id: 3,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/p3.jpg'),
      },
      {
        id: 3,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/p3.jpg'),
      },
      {
        id: 3,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/p3.jpg'),
      },
      {
        id: 3,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/p3.jpg'),
      },
      {
        id: 3,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/p3.jpg'),
      },
      {
        id: 3,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/p3.jpg'),
      },
      {
        id: 3,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/p3.jpg'),
      },
      {
        id: 3,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/p3.jpg'),
      },
      {
        id: 3,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/p3.jpg'),
      },
      {
        id: 3,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/p3.jpg'),
      },
      {
        id: 3,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/p3.jpg'),
      },
      {
        id: 3,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/p3.jpg'),
      },
      {
        id: 3,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/p3.jpg'),
      },
      {
        id: 3,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/p3.jpg'),
      },
      {
        id: 3,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/p3.jpg'),
      },
      {
        id: 3,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/p3.jpg'),
      },
      
      // More plastic seals...
    ],
  };
  
  export default product_data; // Make sure to export the data
  